const EMERGENCY_CONTACTS_ALERT = 'EMERGENCY_CONTACTS_ALERT'
const PROFILE_INCOMPLETE_ALERT = 'PROFILE_INCOMPLETE_ALERT'

module.exports = {
    EMERGENCY_CONTACTS_ALERT,
    PROFILE_INCOMPLETE_ALERT
}
